version: "3.9"

services:

  db:
    image: postgres:16
    container_name: uceshop-db
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - uceshop_pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - uceshop-net
  
  catalog-service:
    build:
      context: ./service-a/catalog-service
      dockerfile: Dockerfile
    container_name: uceshop-catalog
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - uceshop-net  

  order-service:
    container_name: uceshop-order
    build:
      context: ./service-b/order-service
    env_file: .env
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      CATALOG_BASE_URL: http://catalog-service:8080
    depends_on:
      db:
        condition: service_healthy
      catalog-service:
        condition: service_started
    ports:
      - "${ORDER_PORT}:8080"
    networks:
      - uceshop-net

networks:
  uceshop-net:
    driver: bridge

volumes:
  uceshop_pgdata: